"""
rebuild_prey_projections.py
Restore scenario- and year-responsive roe deer and moose densities in the
projection window (2016-2060) of map_data.parquet.

Why this script exists
----------------------
The previous build of map_data.parquet froze the four prey density columns
(D_roe, D_moose, pred_roe_density, pred_moose_density) to a single per-grid
value across every SSP and every projection year, while the canonical model
outputs in `simulation result/deer_density_predictions/` already contain
scenario- and year-responsive predictions (Ghosh, 2026; Riahi et al., 2017).

This script repairs the parquet in place. It:

  1. Locates the canonical eq1 prediction CSVs in the Wolf-model research
     repo (expected under  Desktop/Wolf/Wolf data/simulation result/ ...).
  2. Loads the five SSP CSVs per species (roe, moose) and pivots to a
     wide (GridID, year, scenario) key with both random-forest and
     beta-regression predictions per species.
  3. Left-merges into map_data.parquet, preserves the historical rows
     (scenario == 'historical') untouched, and overwrites the four prey
     columns on projection rows only.
  4. Convention:
        D_roe               <-  D_hat_beta  (beta-regression estimate)
        pred_roe_density    <-  D_hat_rf    (random-forest prediction)
        D_moose             <-  D_hat_beta
        pred_moose_density  <-  D_hat_rf
     Using the two separate estimators for the two app variables keeps them
     genuinely different quantities rather than duplicates.
  5. Rewrites the parquet and prints a variance audit so the repair is
     verifiable without opening the viewer.

Run after any refresh of the eq1 deer-density CSVs, or whenever the parquet
has been regenerated by an upstream pipeline that does not propagate the
prey predictions correctly. Follow this with `build_data_json.py` to refresh
the browser payload.

Author: Dr. Sinchan Ghosh, 2026.
"""

from __future__ import annotations

import os
import sys

try:
    import pandas as pd
except ImportError:
    sys.exit("pandas is required. Install with: pip install pandas fastparquet")

# ---------------------------------------------------------------------------
# Paths
# ---------------------------------------------------------------------------

HERE = os.path.dirname(os.path.abspath(__file__))
PARQUET = os.path.join(HERE, "data", "map_data.parquet")

# Candidate locations for the deer_density_predictions folder. The first
# existing path wins. Edit this list if your repo layout differs.
SRC_CANDIDATES = [
    r"C:\Users\sinch\OneDrive\Desktop\Wolf\Wolf data\simulation result\deer_density_predictions",
    os.path.join(HERE, "..", "..", "..", "..", "..", "Wolf data",
                 "simulation result", "deer_density_predictions"),
    os.path.join(HERE, "..", "..", "..", "..", "Wolf data",
                 "simulation result", "deer_density_predictions"),
]

SCENARIOS = ["ssp119", "ssp126", "ssp245", "ssp370", "ssp585"]
SPECIES = ["roe", "moose"]

# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def find_source() -> str:
    for p in SRC_CANDIDATES:
        if os.path.isdir(p):
            return os.path.abspath(p)
    sys.exit(
        "Could not find 'deer_density_predictions' folder. "
        "Edit SRC_CANDIDATES at the top of this script."
    )


def load_predictions(src: str) -> pd.DataFrame:
    """Return wide-form DataFrame keyed on (GridID, year, scenario) with
    columns D_hat_rf_roe, D_hat_rf_moose, D_hat_beta_roe, D_hat_beta_moose."""
    frames: list[pd.DataFrame] = []
    for spec in SPECIES:
        for scen in SCENARIOS:
            f = os.path.join(src, f"eq1_{scen}_{spec}.csv")
            if not os.path.exists(f):
                print(f"  [missing] {f}", file=sys.stderr)
                continue
            sub = pd.read_csv(f, usecols=["GridID", "year", "D_hat_rf", "D_hat_beta"])
            sub["scenario"] = scen
            sub["species"] = spec
            frames.append(sub)

    if not frames:
        sys.exit("No source CSVs were readable.")

    long = pd.concat(frames, ignore_index=True)
    long["GridID"] = long["GridID"].astype(int)
    long["year"] = long["year"].astype(int)

    wide = long.pivot_table(
        index=["GridID", "year", "scenario"],
        columns="species",
        values=["D_hat_rf", "D_hat_beta"],
        aggfunc="first",
    )
    wide.columns = [f"{a}_{b}" for a, b in wide.columns]
    wide = wide.reset_index()
    return wide


def audit_variance(df: pd.DataFrame, label: str) -> None:
    proj = df[df.scenario != "historical"]
    if proj.empty:
        print(f"  [{label}] no projection rows to audit")
        return
    n_grids = df.GridID.nunique()
    for col in ("D_roe", "D_moose", "pred_roe_density", "pred_moose_density"):
        uniq = proj.groupby("GridID")[col].nunique()
        pct = (uniq > 1).mean() * 100
        median = uniq.median()
        print(f"  [{label}] {col:22s}  grids varying across scen/year: "
              f"{pct:5.1f}% of {n_grids}   median unique vals per grid: {median:.0f}")


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def main() -> None:
    src = find_source()
    print(f"Source CSVs:     {src}")
    print(f"Target parquet:  {PARQUET}")

    if not os.path.exists(PARQUET):
        sys.exit("Target parquet not found.")

    try:
        df = pd.read_parquet(PARQUET, engine="fastparquet")
    except Exception:
        df = pd.read_parquet(PARQUET)

    print(f"Existing parquet: {len(df):,} rows, {df.GridID.nunique()} grids, "
          f"years {int(df.year.min())}-{int(df.year.max())}")
    audit_variance(df, "pre-fix ")

    pred = load_predictions(src)
    print(f"Loaded predictions: {len(pred):,} rows, {pred.GridID.nunique()} grids, "
          f"years {pred.year.min()}-{pred.year.max()}, scenarios {sorted(pred.scenario.unique())}")

    # Merge
    merged = df.merge(pred, on=["GridID", "year", "scenario"], how="left", indicator=True)
    matched = (merged._merge == "both").sum()
    total_proj = (merged.scenario != "historical").sum()
    print(f"Matched projection rows: {matched:,} / {total_proj:,} total projection rows")

    proj_mask = merged.scenario != "historical"

    replacements = [
        ("D_hat_beta_roe",   "D_roe"),
        ("D_hat_rf_roe",     "pred_roe_density"),
        ("D_hat_beta_moose", "D_moose"),
        ("D_hat_rf_moose",   "pred_moose_density"),
    ]
    for src_col, dst_col in replacements:
        if src_col not in merged.columns:
            print(f"  [skip] missing source column {src_col}")
            continue
        has = merged[src_col].notna() & proj_mask
        merged.loc[has, dst_col] = merged.loc[has, src_col].astype(float)
        print(f"  updated  {dst_col:22s}  <-  {src_col:20s}  rows: {int(has.sum()):,}")

    helper_cols = ["D_hat_rf_roe", "D_hat_rf_moose",
                   "D_hat_beta_roe", "D_hat_beta_moose", "_merge"]
    merged = merged.drop(columns=[c for c in helper_cols if c in merged.columns])

    # Preserve original column order where possible
    original_cols = list(df.columns)
    merged = merged[original_cols]

    audit_variance(merged, "post-fix")

    # Write atomically: temp file, then replace
    tmp = PARQUET + ".tmp"
    try:
        merged.to_parquet(tmp, engine="fastparquet", index=False)
    except Exception:
        merged.to_parquet(tmp, index=False)
    os.replace(tmp, PARQUET)
    print(f"Wrote {PARQUET} ({os.path.getsize(PARQUET) / 1024:.0f} KB)")
    print()
    print("Next step:  python docs/tools/scandinavian-sdm/build_data_json.py")
    print("Then:       powershell -ExecutionPolicy Bypass -File publish-wolf-model.ps1")


if __name__ == "__main__":
    main()
